version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing dependencies...
      - npm install
  build:
    commands:
      - echo Build started...
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`
      - zip -r build-output.zip . -x "*.git*" "node_modules/*"
      - aws s3 cp build-output.zip s3://parcenal/build-output.zip
artifacts:
  files:
    - '**/*'
  base-directory: build
