version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - echo Installing root dependencies...
      - npm ci
  build:
    commands:
      - echo Building React app...
      - npm run build
  post_build:
    commands:
      - echo Post build: Preparing EB artifact...
      - mkdir -p deployment
      - cp -r build deployment/build
      - cp -r deployments/package.json deployment/package.json
artifacts:
  base-directory: deployment
  files:
    - '**/*'
