version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20
    commands:
      - echo Installing frontend dependencies...
      - npm install
  build:
    commands:
      - echo Building React app...
      - npm run build
  post_build:
    commands:
      - echo Preparing deployment artifacts...
      - mkdir -p dist
      - cp -r build dist/build
      - cp deployments/package.json dist/package.json
artifacts:
  base-directory: dist
  files:
    - '**/*'
